name: Actualizar JSON LNReader

on:
  schedule:
    - cron: "0 */3 * * *" # cada 3 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'
      - name: Instalar dependencias
        run: npm install axios cheerio
      - name: Ejecutar script
        run: node script.js
      - name: Commit & Push
        run: |
          git config user.name "bot"
          git config user.email "bot@mail.com"
          git add plugins.min.json
          git commit -m "Actualización automática JSON" || echo "Sin cambios"
          git push